// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WordCountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestMessage string                 `protobuf:"bytes,1,opt,name=RequestMessage,proto3" json:"RequestMessage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WordCountRequest) Reset() {
	*x = WordCountRequest{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordCountRequest) ProtoMessage() {}

func (x *WordCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordCountRequest.ProtoReflect.Descriptor instead.
func (*WordCountRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *WordCountRequest) GetRequestMessage() string {
	if x != nil {
		return x.RequestMessage
	}
	return ""
}

type WordCountResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Ct            []*WordCountResponse_WordCountResult `protobuf:"bytes,1,rep,name=ct,proto3" json:"ct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordCountResponse) Reset() {
	*x = WordCountResponse{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordCountResponse) ProtoMessage() {}

func (x *WordCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordCountResponse.ProtoReflect.Descriptor instead.
func (*WordCountResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *WordCountResponse) GetCt() []*WordCountResponse_WordCountResult {
	if x != nil {
		return x.Ct
	}
	return nil
}

type WordCountResponse_WordCountResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordCountResponse_WordCountResult) Reset() {
	*x = WordCountResponse_WordCountResult{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordCountResponse_WordCountResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordCountResponse_WordCountResult) ProtoMessage() {}

func (x *WordCountResponse_WordCountResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordCountResponse_WordCountResult.ProtoReflect.Descriptor instead.
func (*WordCountResponse_WordCountResult) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1, 0}
}

func (x *WordCountResponse_WordCountResult) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WordCountResponse_WordCountResult) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\x05proto\":\n" +
	"\x10WordCountRequest\x12&\n" +
	"\x0eRequestMessage\x18\x01 \x01(\tR\x0eRequestMessage\"\x8a\x01\n" +
	"\x11WordCountResponse\x128\n" +
	"\x02ct\x18\x01 \x03(\v2(.proto.WordCountResponse.WordCountResultR\x02ct\x1a;\n" +
	"\x0fWordCountResult\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2M\n" +
	"\tWordCount\x12@\n" +
	"\tWordCount\x12\x17.proto.WordCountRequest\x1a\x18.proto.WordCountResponse\"\x00B\tZ\a.;protob\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_server_proto_goTypes = []any{
	(*WordCountRequest)(nil),                  // 0: proto.WordCountRequest
	(*WordCountResponse)(nil),                 // 1: proto.WordCountResponse
	(*WordCountResponse_WordCountResult)(nil), // 2: proto.WordCountResponse.WordCountResult
}
var file_server_proto_depIdxs = []int32{
	2, // 0: proto.WordCountResponse.ct:type_name -> proto.WordCountResponse.WordCountResult
	0, // 1: proto.WordCount.WordCount:input_type -> proto.WordCountRequest
	1, // 2: proto.WordCount.WordCount:output_type -> proto.WordCountResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
