// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WordCount_WordCount_FullMethodName = "/wordCount.WordCount/WordCount"
)

// WordCountClient is the client API for WordCount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WordCountClient interface {
	WordCount(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WordCountRequest, WordCountResponse], error)
}

type wordCountClient struct {
	cc grpc.ClientConnInterface
}

func NewWordCountClient(cc grpc.ClientConnInterface) WordCountClient {
	return &wordCountClient{cc}
}

func (c *wordCountClient) WordCount(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WordCountRequest, WordCountResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WordCount_ServiceDesc.Streams[0], WordCount_WordCount_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WordCountRequest, WordCountResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WordCount_WordCountClient = grpc.BidiStreamingClient[WordCountRequest, WordCountResponse]

// WordCountServer is the server API for WordCount service.
// All implementations must embed UnimplementedWordCountServer
// for forward compatibility.
type WordCountServer interface {
	WordCount(grpc.BidiStreamingServer[WordCountRequest, WordCountResponse]) error
	mustEmbedUnimplementedWordCountServer()
}

// UnimplementedWordCountServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWordCountServer struct{}

func (UnimplementedWordCountServer) WordCount(grpc.BidiStreamingServer[WordCountRequest, WordCountResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WordCount not implemented")
}
func (UnimplementedWordCountServer) mustEmbedUnimplementedWordCountServer() {}
func (UnimplementedWordCountServer) testEmbeddedByValue()                   {}

// UnsafeWordCountServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WordCountServer will
// result in compilation errors.
type UnsafeWordCountServer interface {
	mustEmbedUnimplementedWordCountServer()
}

func RegisterWordCountServer(s grpc.ServiceRegistrar, srv WordCountServer) {
	// If the following call pancis, it indicates UnimplementedWordCountServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WordCount_ServiceDesc, srv)
}

func _WordCount_WordCount_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WordCountServer).WordCount(&grpc.GenericServerStream[WordCountRequest, WordCountResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WordCount_WordCountServer = grpc.BidiStreamingServer[WordCountRequest, WordCountResponse]

// WordCount_ServiceDesc is the grpc.ServiceDesc for WordCount service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WordCount_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wordCount.WordCount",
	HandlerType: (*WordCountServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WordCount",
			Handler:       _WordCount_WordCount_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server.proto",
}
